using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Planora.Application.Abstractions.Projects;
using Planora.Application.Abstractions.Security;
using Planora.Application.Abstractions.VModel;
using Planora.Application.Common.VModelTesting;
using Planora.Domain;
using Planora.Domain.Enums;
using Planora.Web.ViewModels.VModel;
namespace Planora.Web.Controllers;
[Authorize]
public sealed class VModelTestingController : VModelArtifactControllerBase
{
 readonly IVModelTestingService service;
 public VModelTestingController(IVModelTestingService service,IProjectService projects,IProjectAccessService access):base(projects,access)=>this.service=service;
 [HttpGet] public async Task<IActionResult> Index(int projectId,VModelTestLevel? testLevel,VModelTestResult? latestResult,bool notExecuted,CancellationToken ct)
 {var(s,e)=await GetScopeAsync(projectId,false,ct);if(e is not null)return e;if(testLevel.HasValue&&!Enum.IsDefined(testLevel.Value)||latestResult.HasValue&&!Enum.IsDefined(latestResult.Value))return BadRequest();var overview=await service.GetOverviewAsync(projectId,ct);if(overview is null)return NotFound();return View(new VModelTestingIndexViewModel{Overview=overview,IsReadOnly=s!.IsReadOnly,CanManagePhases=!s.IsReadOnly&&CanManage(s),CanManageTests=!s.IsReadOnly&&CanManageTesting(s),TestLevel=testLevel,LatestResult=latestResult,NotExecuted=notExecuted,TestCases=await service.GetTestCasesAsync(projectId,new(){TestLevel=testLevel,LatestResult=latestResult,NotExecuted=notExecuted},ct)});}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> InitializePhases(int projectId,CancellationToken ct){var(s,e)=await GetScopeAsync(projectId,true,ct);if(e is not null)return e;if(!CanManage(s!))return Forbid();return Result(await service.EnsurePhasesAsync(projectId,s!.UserId,ct),nameof(Index),projectId);}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> TransitionPhase(TransitionVModelPhaseViewModel m,CancellationToken ct){var(s,e)=await GetScopeAsync(m.ProjectId,true,ct);if(e is not null)return e;if(!CanManage(s!))return Forbid();if(!ModelState.IsValid)return BadRequest();return Result(await service.TransitionPhaseAsync(new(){ProjectId=m.ProjectId,PhaseId=m.PhaseId,ExpectedStatus=m.ExpectedStatus,TargetStatus=m.TargetStatus,ActorUserId=s!.UserId},ct),nameof(Index),m.ProjectId);}
 [HttpGet]public async Task<IActionResult>Create(int projectId,CancellationToken ct){var(s,e)=await GetScopeAsync(projectId,true,ct);if(e is not null)return e;if(!CanManageTesting(s!))return Forbid();return View(new VModelTestCaseFormViewModel{ProjectId=projectId,ProjectName=s!.Project.Name,Identifier=await NextPreview(projectId,ct),ImplementationOptions=await service.GetImplementationOptionsAsync(projectId,ct)});}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Create(int projectId,VModelTestCaseFormViewModel m,CancellationToken ct){var(s,e)=await GetScopeAsync(projectId,true,ct);if(e is not null)return e;if(!CanManageTesting(s!))return Forbid();if(m.ProjectId!=projectId||m.Id!=0)return BadRequest();if(ModelState.IsValid){var r=await service.CreateTestCaseAsync(BuildRequest(m,s!.UserId),ct);if(r.Succeeded){TempData["SuccessMessage"]=r.Message;return RedirectToAction(nameof(Details),new{projectId,id=r.ResourceId});}if(r.Failure!=TestingOperationFailure.Validation)return Fail(r);ModelState.AddModelError("",r.Message);}m.ProjectName=s!.Project.Name;m.Identifier=await NextPreview(projectId,ct);m.ImplementationOptions=await service.GetImplementationOptionsAsync(projectId,ct);return View(m);}
 [HttpGet]public async Task<IActionResult>Details(int projectId,int id,CancellationToken ct){var(s,e)=await GetScopeAsync(projectId,false,ct);if(e is not null)return e;var t=await service.GetTestCaseAsync(projectId,id,ct);if(t is null)return NotFound();var overview=await service.GetOverviewAsync(projectId,ct);var phase=overview!.Phases.SingleOrDefault(x=>x.PhaseType==VModelPhaseCatalog.ForTestLevel(t.TestLevel));return View(new VModelTestCaseDetailsViewModel{TestCase=t,IsReadOnly=s!.IsReadOnly,CanEdit=!s.IsReadOnly&&CanManageTesting(s),CanExecute=!s.IsReadOnly&&CanManageTesting(s)&&phase?.Status!=VModelPhaseStatus.NotStarted});}
 [HttpGet]public async Task<IActionResult>Edit(int projectId,int id,CancellationToken ct){var(s,e)=await GetScopeAsync(projectId,true,ct);if(e is not null)return e;if(!CanManageTesting(s!))return Forbid();var t=await service.GetTestCaseAsync(projectId,id,ct);if(t is null)return NotFound();return View(Form(t,await service.GetImplementationOptionsAsync(projectId,ct)));}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Edit(int projectId,int id,VModelTestCaseFormViewModel m,CancellationToken ct){var(s,e)=await GetScopeAsync(projectId,true,ct);if(e is not null)return e;if(!CanManageTesting(s!))return Forbid();if(m.ProjectId!=projectId||m.Id!=id)return BadRequest();if(ModelState.IsValid){var r=await service.UpdateTestCaseAsync(new(){ProjectId=projectId,TestCaseId=id,Title=m.Title,Description=m.Description,TestLevel=m.TestLevel,Preconditions=m.Preconditions,TestSteps=m.TestSteps,ExpectedResult=m.ExpectedResult,ImplementationArtifactIds=m.ImplementationArtifactIds,ActorUserId=s!.UserId},ct);if(r.Succeeded){TempData["SuccessMessage"]=r.Message;return RedirectToAction(nameof(Details),new{projectId,id});}if(r.Failure!=TestingOperationFailure.Validation)return Fail(r);ModelState.AddModelError("",r.Message);}var current=await service.GetTestCaseAsync(projectId,id,ct);if(current is null)return NotFound();m.ProjectName=s!.Project.Name;m.Identifier=current.Identifier;m.ImplementationOptions=await service.GetImplementationOptionsAsync(projectId,ct);return View(m);}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Execute(ExecuteVModelTestViewModel m,CancellationToken ct){var(s,e)=await GetScopeAsync(m.ProjectId,true,ct);if(e is not null)return e;if(!CanManageTesting(s!))return Forbid();if(!ModelState.IsValid)return BadRequest();var r=await service.ExecuteAsync(new(){ProjectId=m.ProjectId,TestCaseId=m.TestCaseId,Result=m.Result,ActualResult=m.ActualResult,Notes=m.Notes,ActorUserId=s!.UserId},ct);if(!r.Succeeded)return Fail(r);TempData["SuccessMessage"]=r.Message;return RedirectToAction(nameof(Details),new{projectId=m.ProjectId,id=m.TestCaseId});}
 [HttpGet]public async Task<IActionResult>Validation(int projectId,CancellationToken ct){var(s,e)=await GetScopeAsync(projectId,false,ct);if(e is not null)return e;return View(new VModelValidationViewModel{Overview=(await service.GetOverviewAsync(projectId,ct))!,IsReadOnly=s!.IsReadOnly,CanValidate=!s.IsReadOnly&&CanManageTesting(s)});}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Validate(ValidateVModelPhaseViewModel m,CancellationToken ct){var(s,e)=await GetScopeAsync(m.ProjectId,true,ct);if(e is not null)return e;if(!CanManageTesting(s!))return Forbid();if(!ModelState.IsValid)return BadRequest();return Result(await service.ValidatePhaseAsync(new(){ProjectId=m.ProjectId,PhaseId=m.PhaseId,Result=m.Result,Notes=m.Notes,ActorUserId=s!.UserId},ct),nameof(Validation),m.ProjectId);}
 async Task<string> NextPreview(int projectId,CancellationToken ct){var cases=await service.GetTestCasesAsync(projectId,null,ct);int max=cases.Select(x=>int.TryParse(x.Identifier.AsSpan(3),out int n)?n:0).DefaultIfEmpty().Max();return$"TC-{max+1:D3}";}
 static CreateVModelTestCaseRequest BuildRequest(VModelTestCaseFormViewModel m,string uid)=>new(){ProjectId=m.ProjectId,Title=m.Title,Description=m.Description,TestLevel=m.TestLevel,Preconditions=m.Preconditions,TestSteps=m.TestSteps,ExpectedResult=m.ExpectedResult,ImplementationArtifactIds=m.ImplementationArtifactIds,ActorUserId=uid};static VModelTestCaseFormViewModel Form(VModelTestCaseDetails t,IReadOnlyList<ImplementationTestOption> options)=>new(){Id=t.Id,ProjectId=t.ProjectId,ProjectName=t.ProjectName,Identifier=t.Identifier,Title=t.Title,Description=t.Description,TestLevel=t.TestLevel,Preconditions=t.Preconditions,TestSteps=t.TestSteps,ExpectedResult=t.ExpectedResult,ImplementationArtifactIds=t.Implementations.Select(x=>x.Id).ToList(),ImplementationOptions=options};IActionResult Result(TestingOperationResult r,string action,int pid){if(!r.Succeeded)return Fail(r);TempData["SuccessMessage"]=r.Message;return RedirectToAction(action,new{projectId=pid});}IActionResult Fail(TestingOperationResult r)=>r.Failure switch{TestingOperationFailure.NotFound=>NotFound(r.Message),TestingOperationFailure.Forbidden=>StatusCode(403,r.Message),TestingOperationFailure.ReadOnly or TestingOperationFailure.Conflict=>StatusCode(409,r.Message),_=>BadRequest(r.Message)};
}
