using System.ComponentModel.DataAnnotations;
using Planora.Application.Common.VModelTesting;
using Planora.Domain.Enums;
namespace Planora.Web.ViewModels.VModel;
public sealed class VModelTestingIndexViewModel { public TestingProjectOverview Overview{get;init;}=new(); public bool IsReadOnly{get;init;} public bool CanManagePhases{get;init;} public bool CanManageTests{get;init;} public VModelTestLevel? TestLevel{get;init;} public VModelTestResult? LatestResult{get;init;} public bool NotExecuted{get;init;} public IReadOnlyList<VModelTestCaseSummary> TestCases{get;init;}=[]; }
public sealed class VModelTestCaseDetailsViewModel { public VModelTestCaseDetails TestCase{get;init;}=new(); public bool IsReadOnly{get;init;} public bool CanEdit{get;init;} public bool CanExecute{get;init;} }
public sealed class VModelTestCaseFormViewModel { public int Id{get;set;} public int ProjectId{get;set;} public string ProjectName{get;set;}=string.Empty; public string Identifier{get;set;}="TC-001"; [Required,StringLength(200)]public string Title{get;set;}=string.Empty; [Required,StringLength(3000)]public string Description{get;set;}=string.Empty; [EnumDataType(typeof(VModelTestLevel))]public VModelTestLevel TestLevel{get;set;}=VModelTestLevel.Unit; [StringLength(2000)]public string? Preconditions{get;set;} [Required,StringLength(5000)]public string TestSteps{get;set;}=string.Empty; [Required,StringLength(3000)]public string ExpectedResult{get;set;}=string.Empty; public List<int> ImplementationArtifactIds{get;set;}=[]; public IReadOnlyList<ImplementationTestOption> ImplementationOptions{get;set;}=[]; }
public sealed class ExecuteVModelTestViewModel { public int ProjectId{get;set;} public int TestCaseId{get;set;} [EnumDataType(typeof(VModelTestResult))]public VModelTestResult Result{get;set;} [Required,StringLength(3000)]public string ActualResult{get;set;}=string.Empty; [StringLength(3000)]public string? Notes{get;set;} }
public sealed class TransitionVModelPhaseViewModel { public int ProjectId{get;set;} public int PhaseId{get;set;} public VModelPhaseStatus ExpectedStatus{get;set;} public VModelPhaseStatus TargetStatus{get;set;} }
public sealed class ValidateVModelPhaseViewModel { public int ProjectId{get;set;} public int PhaseId{get;set;} [EnumDataType(typeof(VModelValidationResult))]public VModelValidationResult Result{get;set;} [Required,StringLength(3000)]public string Notes{get;set;}=string.Empty; }
public sealed class VModelValidationViewModel { public TestingProjectOverview Overview{get;init;}=new(); public bool IsReadOnly{get;init;} public bool CanValidate{get;init;} }
