using Planora.Domain.Enums;
namespace Planora.Application.Common.VModelTesting;
public sealed class VModelPhaseSummary { public int Id{get;init;} public VModelPhaseType PhaseType{get;init;} public int PhaseOrder{get;init;} public VModelPhaseStatus Status{get;init;} public DateTime? StartedAt{get;init;} public DateTime? CompletedAt{get;init;} public VModelValidationResult? LatestValidationResult{get;init;} public DateTime? LatestValidationAt{get;init;} public IReadOnlyList<VModelPhaseValidationSummary> Validations{get;set;}=[]; }
public sealed class VModelPhaseValidationSummary { public int Id{get;init;} public VModelValidationResult Result{get;init;} public string Notes{get;init;}=string.Empty; public string ValidatorName{get;init;}=string.Empty; public DateTime ValidatedAt{get;init;} }
public sealed class TestingProjectOverview { public int ProjectId{get;init;} public string ProjectName{get;init;}=string.Empty; public IReadOnlyList<VModelPhaseSummary> Phases{get;init;}=[]; }
public sealed class ImplementationTestOption { public int Id{get;init;} public string Identifier{get;init;}=string.Empty; public string Title{get;init;}=string.Empty; }
public sealed class VModelTestExecutionSummary { public int Id{get;init;} public VModelTestResult Result{get;init;} public string ActualResult{get;init;}=string.Empty; public string? Notes{get;init;} public string ExecutorName{get;init;}=string.Empty; public DateTime ExecutedAt{get;init;} public IReadOnlyList<ExecutionIssueSummary> Issues{get;set;}=[]; }
public sealed class ExecutionIssueSummary { public int Id{get;init;} public string Title{get;init;}=string.Empty; public IssueStatus Status{get;init;} }
public class VModelTestCaseSummary { public int Id{get;init;} public int ProjectId{get;init;} public string Identifier{get;init;}=string.Empty; public string Title{get;init;}=string.Empty; public VModelTestLevel TestLevel{get;init;} public int LinkedImplementationCount{get;init;} public VModelTestResult? LatestResult{get;init;} public DateTime? LastExecutedAt{get;init;} public string CreatorUserId{get;init;}=string.Empty; }
public sealed class VModelTestCaseDetails : VModelTestCaseSummary { public string ProjectName{get;init;}=string.Empty; public string Description{get;init;}=string.Empty; public string? Preconditions{get;init;} public string TestSteps{get;init;}=string.Empty; public string ExpectedResult{get;init;}=string.Empty; public IReadOnlyList<ImplementationTestOption> Implementations{get;set;}=[]; public IReadOnlyList<Planora.Application.Common.Requirements.RequirementDesignArtifactSummary> Designs{get;set;}=[]; public IReadOnlyList<RequirementArtifactTraceSummary> Requirements{get;set;}=[]; public IReadOnlyList<VModelTestExecutionSummary> Executions{get;set;}=[]; }
public sealed class RequirementArtifactTraceSummary { public int Id{get;init;} public string Identifier{get;init;}=string.Empty; public string Title{get;init;}=string.Empty; public RequirementStatus Status{get;init;} }
public sealed class VModelTestCaseFilter { public VModelTestLevel? TestLevel{get;init;} public VModelTestResult? LatestResult{get;init;} public bool NotExecuted{get;init;} }
public class CreateVModelTestCaseRequest { public int ProjectId{get;init;} public string Title{get;init;}=string.Empty; public string Description{get;init;}=string.Empty; public VModelTestLevel TestLevel{get;init;} public string? Preconditions{get;init;} public string TestSteps{get;init;}=string.Empty; public string ExpectedResult{get;init;}=string.Empty; public IReadOnlyList<int> ImplementationArtifactIds{get;init;}=[]; public string ActorUserId{get;init;}=string.Empty; }
public sealed class UpdateVModelTestCaseRequest : CreateVModelTestCaseRequest { public int TestCaseId{get;init;} }
public sealed class TransitionPhaseRequest { public int ProjectId{get;init;} public int PhaseId{get;init;} public VModelPhaseStatus ExpectedStatus{get;init;} public VModelPhaseStatus TargetStatus{get;init;} public string ActorUserId{get;init;}=string.Empty; }
public sealed class ExecuteVModelTestCaseRequest { public int ProjectId{get;init;} public int TestCaseId{get;init;} public VModelTestResult Result{get;init;} public string ActualResult{get;init;}=string.Empty; public string? Notes{get;init;} public string ActorUserId{get;init;}=string.Empty; }
public sealed class ValidateVModelPhaseRequest { public int ProjectId{get;init;} public int PhaseId{get;init;} public VModelValidationResult Result{get;init;} public string Notes{get;init;}=string.Empty; public string ActorUserId{get;init;}=string.Empty; }
public sealed class LinkVModelTestIssueRequest { public int ProjectId{get;init;} public int ExecutionId{get;init;} public int IssueId{get;init;} public string ActorUserId{get;init;}=string.Empty; }
public enum TestingOperationFailure { None=0,Validation,NotFound,Forbidden,ReadOnly,Conflict }
public sealed class TestingOperationResult { public bool Succeeded{get;init;} public int? ResourceId{get;init;} public string? Identifier{get;init;} public TestingOperationFailure Failure{get;init;} public string Message{get;init;}=string.Empty; public static TestingOperationResult Success(int? id,string message,string? identifier=null)=>new(){Succeeded=true,ResourceId=id,Message=message,Identifier=identifier}; public static TestingOperationResult Failed(TestingOperationFailure f,string m)=>new(){Failure=f,Message=m}; }
