using System.Collections.Concurrent;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Planora.Application.Abstractions.Common;
using Planora.Application.Abstractions.VModel;
using Planora.Application.Common.Security;
using Planora.Application.Common.VModelTesting;
using Planora.Domain;
using Planora.Domain.Entities;
using Planora.Domain.Enums;
using Planora.Infrastructure.Persistence;
namespace Planora.Infrastructure.VModel;

public sealed class VModelTestingService : IVModelTestingService
{
 const int RetryLimit=3; static readonly ConcurrentDictionary<int,SemaphoreSlim> Locks=new();
 readonly ApplicationDbContext db; readonly IClock clock;
 public VModelTestingService(ApplicationDbContext db,IClock clock){this.db=db;this.clock=clock;}

 public async Task<TestingProjectOverview?> GetOverviewAsync(int projectId,CancellationToken ct=default)
 {
  var project=await db.Projects.AsNoTracking().Where(x=>x.Id==projectId&&x.Methodology==ProjectMethodology.VModel).Select(x=>new{x.Id,x.Name}).SingleOrDefaultAsync(ct); if(project is null)return null;
  var phases=await db.VModelPhases.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderBy(x=>x.PhaseOrder).Select(x=>new VModelPhaseSummary{Id=x.Id,PhaseType=x.PhaseType,PhaseOrder=x.PhaseOrder,Status=x.Status,StartedAt=x.StartedAt,CompletedAt=x.CompletedAt,LatestValidationResult=x.Validations.OrderByDescending(v=>v.ValidatedAt).ThenByDescending(v=>v.Id).Select(v=>(VModelValidationResult?)v.Result).FirstOrDefault(),LatestValidationAt=x.Validations.OrderByDescending(v=>v.ValidatedAt).ThenByDescending(v=>v.Id).Select(v=>(DateTime?)v.ValidatedAt).FirstOrDefault()}).ToListAsync(ct);
   var phaseIds=phases.Select(x=>x.Id).ToList();
   var validations=await db.VModelPhaseValidations.AsNoTracking().Where(x=>phaseIds.Contains(x.VModelPhaseId)).OrderByDescending(x=>x.ValidatedAt).ThenByDescending(x=>x.Id).Select(x=>new{x.VModelPhaseId,Summary=new VModelPhaseValidationSummary{Id=x.Id,Result=x.Result,Notes=x.Notes,ValidatorName=db.Users.Where(u=>u.Id==x.ValidatedByUserId).Select(u=>u.FullName!=""?u.FullName:u.UserName??u.Id).FirstOrDefault()??x.ValidatedByUserId,ValidatedAt=x.ValidatedAt}}).ToListAsync(ct);
   var validationsByPhase=validations.GroupBy(x=>x.VModelPhaseId).ToDictionary(x=>x.Key,x=>(IReadOnlyList<VModelPhaseValidationSummary>)x.Select(v=>v.Summary).ToList());
   foreach(var p in phases)p.Validations=validationsByPhase.GetValueOrDefault(p.Id)??[];
  return new(){ProjectId=project.Id,ProjectName=project.Name,Phases=phases};
 }
 public async Task<TestingOperationResult> EnsurePhasesAsync(int projectId,string actorUserId,CancellationToken ct=default)
 {
  var a=await Access(projectId,actorUserId,ct); if(a.Error is not null)return a.Error; if(a.Project!.Status==ProjectStatus.Archived)return ReadOnly(); if(!CanPhase(a.Actor!))return Forbidden();
  var existing=(await db.VModelPhases.Where(x=>x.ProjectId==projectId).Select(x=>x.PhaseType).ToListAsync(ct)).ToHashSet();
  foreach(var (type,index) in VModelPhaseCatalog.Ordered.Select((x,i)=>(x,i)))if(!existing.Contains(type))db.VModelPhases.Add(new(){ProjectId=projectId,PhaseType=type,PhaseOrder=index+1,Status=VModelPhaseStatus.NotStarted,CreatedAt=clock.UtcNow});
  try{await db.SaveChangesAsync(ct);}catch(DbUpdateException){return Conflict("V-Model phases were initialized concurrently. Refresh and try again.");} return Ok(null,"V-Model phases are ready.");
 }
 public async Task<TestingOperationResult> TransitionPhaseAsync(TransitionPhaseRequest r,CancellationToken ct=default)
 {
  if(!Enum.IsDefined(r.ExpectedStatus)||!Enum.IsDefined(r.TargetStatus))return Invalid("The phase status is invalid.");
  var phase=await db.VModelPhases.SingleOrDefaultAsync(x=>x.Id==r.PhaseId&&x.ProjectId==r.ProjectId,ct);if(phase is null)return NotFound("The V-Model phase was not found.");
  var a=await Access(r.ProjectId,r.ActorUserId,ct);if(a.Error is not null)return a.Error;if(a.Project!.Status==ProjectStatus.Archived)return ReadOnly();if(!CanPhase(a.Actor!))return Forbidden();
  if(phase.Status!=r.ExpectedStatus)return Conflict("The phase status changed. Refresh and try again.");
  if(phase.Status==VModelPhaseStatus.NotStarted&&r.TargetStatus==VModelPhaseStatus.InProgress){if(phase.PhaseOrder>1&&!await db.VModelPhases.AnyAsync(x=>x.ProjectId==r.ProjectId&&x.PhaseOrder==phase.PhaseOrder-1&&x.Status==VModelPhaseStatus.Completed,ct))return Conflict("The previous V-Model phase must be Completed first.");phase.Status=r.TargetStatus;phase.StartedAt=clock.UtcNow;}
  else if(phase.Status==VModelPhaseStatus.InProgress&&r.TargetStatus==VModelPhaseStatus.Completed){phase.Status=r.TargetStatus;phase.CompletedAt=clock.UtcNow;}
  else return Invalid("That V-Model phase transition is not allowed."); phase.UpdatedAt=clock.UtcNow;db.ActivityLogs.Add(Audit(r.TargetStatus==VModelPhaseStatus.InProgress?"VModelPhaseStarted":"VModelPhaseCompleted","VModelPhase",phase.PhaseType.ToString(),r.ProjectId,r.ActorUserId));await db.SaveChangesAsync(ct);return Ok(phase.Id,"Phase status updated.");
 }
 public async Task<IReadOnlyList<VModelTestCaseSummary>> GetTestCasesAsync(int projectId,VModelTestCaseFilter? f=null,CancellationToken ct=default)
 {
  IQueryable<VModelTestCase> q=db.VModelTestCases.AsNoTracking().Where(x=>x.ProjectId==projectId);if(f?.TestLevel is not null)q=q.Where(x=>x.TestLevel==f.TestLevel);if(f?.NotExecuted==true)q=q.Where(x=>!x.Executions.Any());if(f?.LatestResult is not null)q=q.Where(x=>x.Executions.OrderByDescending(e=>e.ExecutedAt).ThenByDescending(e=>e.Id).Select(e=>(VModelTestResult?)e.Result).FirstOrDefault()==f.LatestResult);
  return await q.OrderBy(x=>x.Identifier).Select(x=>new VModelTestCaseSummary{Id=x.Id,ProjectId=x.ProjectId,Identifier=x.Identifier,Title=x.Title,TestLevel=x.TestLevel,LinkedImplementationCount=x.ImplementationArtifacts.Count,LatestResult=x.Executions.OrderByDescending(e=>e.ExecutedAt).ThenByDescending(e=>e.Id).Select(e=>(VModelTestResult?)e.Result).FirstOrDefault(),LastExecutedAt=x.Executions.OrderByDescending(e=>e.ExecutedAt).ThenByDescending(e=>e.Id).Select(e=>(DateTime?)e.ExecutedAt).FirstOrDefault(),CreatorUserId=x.CreatedByUserId}).ToListAsync(ct);
 }
 public async Task<VModelTestCaseDetails?> GetTestCaseAsync(int projectId,int id,CancellationToken ct=default)
 {
  var t=await db.VModelTestCases.AsNoTracking().Where(x=>x.Id==id&&x.ProjectId==projectId).Select(x=>new VModelTestCaseDetails{Id=x.Id,ProjectId=x.ProjectId,ProjectName=x.Project.Name,Identifier=x.Identifier,Title=x.Title,Description=x.Description,TestLevel=x.TestLevel,Preconditions=x.Preconditions,TestSteps=x.TestSteps,ExpectedResult=x.ExpectedResult,LinkedImplementationCount=x.ImplementationArtifacts.Count,LatestResult=x.Executions.OrderByDescending(e=>e.ExecutedAt).ThenByDescending(e=>e.Id).Select(e=>(VModelTestResult?)e.Result).FirstOrDefault(),LastExecutedAt=x.Executions.OrderByDescending(e=>e.ExecutedAt).ThenByDescending(e=>e.Id).Select(e=>(DateTime?)e.ExecutedAt).FirstOrDefault(),CreatorUserId=x.CreatedByUserId}).SingleOrDefaultAsync(ct);if(t is null)return null;
  t.Implementations=await db.VModelTestCaseImplementationArtifacts.AsNoTracking().Where(x=>x.VModelTestCaseId==id&&x.ImplementationArtifact.ProjectId==projectId).Select(x=>new ImplementationTestOption{Id=x.ImplementationArtifactId,Identifier=x.ImplementationArtifact.Identifier,Title=x.ImplementationArtifact.Title}).OrderBy(x=>x.Identifier).ToListAsync(ct);
  var implIds=t.Implementations.Select(x=>x.Id).ToList();var designs=await db.ImplementationArtifactDesigns.AsNoTracking().Where(x=>implIds.Contains(x.ImplementationArtifactId)&&x.DesignArtifact.ProjectId==projectId).Select(x=>new Planora.Application.Common.Requirements.RequirementDesignArtifactSummary{Id=x.DesignArtifactId,Identifier=x.DesignArtifact.Identifier,Title=x.DesignArtifact.Title,Type=x.DesignArtifact.Type}).Distinct().ToListAsync(ct);t.Designs=designs;
  var designIds=designs.Select(x=>x.Id).ToList();t.Requirements=await db.DesignArtifactRequirements.AsNoTracking().Where(x=>designIds.Contains(x.DesignArtifactId)&&x.Requirement.ProjectId==projectId).Select(x=>new RequirementArtifactTraceSummary{Id=x.RequirementId,Identifier=x.Requirement.Identifier,Title=x.Requirement.Title,Status=x.Requirement.Status}).Distinct().OrderBy(x=>x.Identifier).ToListAsync(ct);
   t.Executions=await db.VModelTestExecutions.AsNoTracking().Where(x=>x.VModelTestCaseId==id).OrderByDescending(x=>x.ExecutedAt).ThenByDescending(x=>x.Id).Select(x=>new VModelTestExecutionSummary{Id=x.Id,Result=x.Result,ActualResult=x.ActualResult,Notes=x.Notes,ExecutorName=db.Users.Where(u=>u.Id==x.ExecutedByUserId).Select(u=>u.FullName!=""?u.FullName:u.UserName??u.Id).FirstOrDefault()??x.ExecutedByUserId,ExecutedAt=x.ExecutedAt}).ToListAsync(ct);
   var executionIds=t.Executions.Select(x=>x.Id).ToList();
   var executionIssues=await db.VModelTestExecutionIssues.AsNoTracking().Where(x=>executionIds.Contains(x.VModelTestExecutionId)).Select(x=>new{x.VModelTestExecutionId,Summary=new ExecutionIssueSummary{Id=x.IssueId,Title=x.Issue.Title,Status=x.Issue.Status}}).ToListAsync(ct);
   var issuesByExecution=executionIssues.GroupBy(x=>x.VModelTestExecutionId).ToDictionary(x=>x.Key,x=>(IReadOnlyList<ExecutionIssueSummary>)x.Select(i=>i.Summary).ToList());
   foreach(var e in t.Executions)e.Issues=issuesByExecution.GetValueOrDefault(e.Id)??[];
   return t;
 }
 public async Task<IReadOnlyList<ImplementationTestOption>> GetImplementationOptionsAsync(int projectId,CancellationToken ct=default)=>await db.ImplementationArtifacts.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderBy(x=>x.Identifier).Select(x=>new ImplementationTestOption{Id=x.Id,Identifier=x.Identifier,Title=x.Title}).ToListAsync(ct);
 public async Task<TestingOperationResult> CreateTestCaseAsync(CreateVModelTestCaseRequest r,CancellationToken ct=default)
 {
  var v=ValidateTest(r);if(v is not null)return Invalid(v);var a=await Access(r.ProjectId,r.ActorUserId,ct);if(a.Error is not null)return a.Error;if(a.Project!.Status==ProjectStatus.Archived)return ReadOnly();if(!CanTest(a.Actor!))return Forbidden();var links=await Implementations(r.ProjectId,r.ImplementationArtifactIds,ct);if(links.Count!=r.ImplementationArtifactIds.Count)return Invalid("Every linked implementation artifact must belong to this project.");var gate=Locks.GetOrAdd(r.ProjectId,_=>new(1,1));await gate.WaitAsync(ct);try{for(int n=1;n<=RetryLimit;n++){string identifier=await NextId(r.ProjectId,ct);var t=new VModelTestCase{ProjectId=r.ProjectId,Identifier=identifier,Title=r.Title.Trim(),Description=r.Description.Trim(),TestLevel=r.TestLevel,Preconditions=Opt(r.Preconditions),TestSteps=r.TestSteps.Trim(),ExpectedResult=r.ExpectedResult.Trim(),CreatedByUserId=r.ActorUserId,CreatedAt=clock.UtcNow};db.Add(t);var added=new List<object>{t};foreach(var i in links){var l=new VModelTestCaseImplementationArtifact{VModelTestCase=t,ImplementationArtifactId=i.Id};db.Add(l);added.Add(l);var al=Audit("VModelTestCaseImplementationLinked",nameof(VModelTestCase),identifier,r.ProjectId,r.ActorUserId);db.Add(al);added.Add(al);}var audit=Audit("VModelTestCaseCreated",nameof(VModelTestCase),identifier,r.ProjectId,r.ActorUserId);db.Add(audit);added.Add(audit);try{await db.SaveChangesAsync(ct);return Ok(t.Id,"Test case created.",identifier);}catch(DbUpdateException ex)when(Collision(ex)&&n<RetryLimit){Detach(added);}catch(DbUpdateException ex)when(Collision(ex)){Detach(added);return Conflict("The test case identifier was allocated concurrently. Please try again.");}}}finally{gate.Release();}return Conflict("The test case identifier could not be allocated.");
 }
 public async Task<TestingOperationResult> UpdateTestCaseAsync(UpdateVModelTestCaseRequest r,CancellationToken ct=default)
 {
  var v=ValidateTest(r);if(v is not null)return Invalid(v);var t=await db.VModelTestCases.Include(x=>x.ImplementationArtifacts).ThenInclude(x=>x.ImplementationArtifact).SingleOrDefaultAsync(x=>x.Id==r.TestCaseId&&x.ProjectId==r.ProjectId,ct);if(t is null)return NotFound("The test case was not found.");var a=await Access(r.ProjectId,r.ActorUserId,ct);if(a.Error is not null)return a.Error;if(a.Project!.Status==ProjectStatus.Archived)return ReadOnly();if(!CanTest(a.Actor!))return Forbidden();var links=await Implementations(r.ProjectId,r.ImplementationArtifactIds,ct);if(links.Count!=r.ImplementationArtifactIds.Count)return Invalid("Every linked implementation artifact must belong to this project.");t.Title=r.Title.Trim();t.Description=r.Description.Trim();t.TestLevel=r.TestLevel;t.Preconditions=Opt(r.Preconditions);t.TestSteps=r.TestSteps.Trim();t.ExpectedResult=r.ExpectedResult.Trim();t.UpdatedByUserId=r.ActorUserId;t.UpdatedAt=clock.UtcNow;var selected=r.ImplementationArtifactIds.ToHashSet();foreach(var l in t.ImplementationArtifacts.Where(x=>!selected.Contains(x.ImplementationArtifactId)).ToList()){db.Remove(l);db.Add(Audit("VModelTestCaseImplementationUnlinked",nameof(VModelTestCase),t.Identifier,r.ProjectId,r.ActorUserId));}var existing=t.ImplementationArtifacts.Select(x=>x.ImplementationArtifactId).ToHashSet();foreach(var i in links.Where(x=>!existing.Contains(x.Id))){db.Add(new VModelTestCaseImplementationArtifact{VModelTestCaseId=t.Id,ImplementationArtifactId=i.Id});db.Add(Audit("VModelTestCaseImplementationLinked",nameof(VModelTestCase),t.Identifier,r.ProjectId,r.ActorUserId));}db.Add(Audit("VModelTestCaseEdited",nameof(VModelTestCase),t.Identifier,r.ProjectId,r.ActorUserId));await db.SaveChangesAsync(ct);return Ok(t.Id,"Test case updated.",t.Identifier);
 }
 public async Task<TestingOperationResult> ExecuteAsync(ExecuteVModelTestCaseRequest r,CancellationToken ct=default)
 {
  if(!Enum.IsDefined(r.Result)||string.IsNullOrWhiteSpace(r.ActualResult)||r.ActualResult.Trim().Length>3000||r.Notes?.Trim().Length>3000)return Invalid("A valid result and actual result are required.");var t=await db.VModelTestCases.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==r.TestCaseId&&x.ProjectId==r.ProjectId,ct);if(t is null)return NotFound("The test case was not found.");var a=await Access(r.ProjectId,r.ActorUserId,ct);if(a.Error is not null)return a.Error;if(a.Project!.Status==ProjectStatus.Archived)return ReadOnly();if(!CanTest(a.Actor!))return Forbidden();var phaseType=VModelPhaseCatalog.ForTestLevel(t.TestLevel);var phase=await db.VModelPhases.AsNoTracking().SingleOrDefaultAsync(x=>x.ProjectId==r.ProjectId&&x.PhaseType==phaseType,ct);if(phase is null||phase.Status==VModelPhaseStatus.NotStarted)return Conflict("The corresponding testing phase must be In Progress or Completed before execution.");var e=new VModelTestExecution{VModelTestCaseId=t.Id,Result=r.Result,ActualResult=r.ActualResult.Trim(),Notes=Opt(r.Notes),ExecutedByUserId=r.ActorUserId,ExecutedAt=clock.UtcNow};db.Add(e);db.Add(Audit("VModelTestExecuted",nameof(VModelTestCase),t.Identifier,r.ProjectId,r.ActorUserId));await db.SaveChangesAsync(ct);return Ok(e.Id,"Test execution recorded.");
 }
 public async Task<TestingOperationResult> ValidatePhaseAsync(ValidateVModelPhaseRequest r,CancellationToken ct=default)
 {
  if(!Enum.IsDefined(r.Result)||string.IsNullOrWhiteSpace(r.Notes)||r.Notes.Trim().Length>3000)return Invalid("A valid result and validation notes are required.");var p=await db.VModelPhases.SingleOrDefaultAsync(x=>x.Id==r.PhaseId&&x.ProjectId==r.ProjectId,ct);if(p is null)return NotFound("The V-Model phase was not found.");var a=await Access(r.ProjectId,r.ActorUserId,ct);if(a.Error is not null)return a.Error;if(a.Project!.Status==ProjectStatus.Archived)return ReadOnly();if(!CanTest(a.Actor!))return Forbidden();if(p.Status!=VModelPhaseStatus.Completed)return Conflict("Only completed phases can be validated.");var v=new VModelPhaseValidation{VModelPhaseId=p.Id,Result=r.Result,Notes=r.Notes.Trim(),ValidatedByUserId=r.ActorUserId,ValidatedAt=clock.UtcNow};db.Add(v);db.Add(Audit("VModelPhaseValidated",nameof(VModelPhase),p.PhaseType.ToString(),r.ProjectId,r.ActorUserId));await db.SaveChangesAsync(ct);return Ok(v.Id,"Phase validation recorded.");
 }
 public async Task<TestingOperationResult> LinkIssueAsync(LinkVModelTestIssueRequest r,CancellationToken ct=default)
 {
  var e=await db.VModelTestExecutions.AsNoTracking().Include(x=>x.VModelTestCase).SingleOrDefaultAsync(x=>x.Id==r.ExecutionId&&x.VModelTestCase.ProjectId==r.ProjectId,ct);if(e is null)return NotFound("The test execution was not found.");var a=await Access(r.ProjectId,r.ActorUserId,ct);if(a.Error is not null)return a.Error;if(a.Project!.Status==ProjectStatus.Archived)return ReadOnly();if(!CanTest(a.Actor!))return Forbidden();if(e.Result!=VModelTestResult.Fail)return Invalid("Issues may be linked only to failed test executions.");if(!await db.Issues.AnyAsync(x=>x.Id==r.IssueId&&x.ProjectId==r.ProjectId,ct))return Invalid("The issue does not belong to this project.");if(await db.VModelTestExecutionIssues.AnyAsync(x=>x.VModelTestExecutionId==r.ExecutionId&&x.IssueId==r.IssueId,ct))return Conflict("This issue is already linked.");db.Add(new VModelTestExecutionIssue{VModelTestExecutionId=r.ExecutionId,IssueId=r.IssueId});db.Add(Audit("VModelTestIssueLinked",nameof(VModelTestExecution),r.ExecutionId.ToString(),r.ProjectId,r.ActorUserId));await db.SaveChangesAsync(ct);return Ok(r.ExecutionId,"Issue linked to failed execution.");
 }
 async Task<(Project? Project,Actor? Actor,TestingOperationResult? Error)> Access(int projectId,string uid,CancellationToken ct){var p=await db.Projects.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==projectId,ct);if(p is null)return(null,null,NotFound("The project was not found."));if(p.Methodology!=ProjectMethodology.VModel)return(null,null,Forbidden("V-Model testing is available only for V-Model projects."));var roles=await(from ur in db.UserRoles.AsNoTracking()join role in db.Roles.AsNoTracking()on ur.RoleId equals role.Id where ur.UserId==uid select role.Name).ToListAsync(ct);bool admin=roles.Contains(SystemRoles.Admin);var pr=await db.ProjectMembers.AsNoTracking().Where(x=>x.ProjectId==projectId&&x.UserId==uid).Select(x=>(ProjectMemberRole?)x.Role).SingleOrDefaultAsync(ct);if(!admin&&pr is null)return(null,null,Forbidden("You are not a member of this project."));return(p,new(admin,roles.Contains(SystemRoles.ProjectManager),roles.Contains(SystemRoles.QaTester),pr),null);}
 static bool CanPhase(Actor a)=>a.Admin||a.Manager&&a.Role==ProjectMemberRole.ProjectManager;static bool CanTest(Actor a)=>a.Admin||a.Qa&&a.Role==ProjectMemberRole.QaTester;
 async Task<List<ImplementationArtifact>> Implementations(int pid,IReadOnlyList<int> ids,CancellationToken ct)=>await db.ImplementationArtifacts.AsNoTracking().Where(x=>ids.Contains(x.Id)&&x.ProjectId==pid).ToListAsync(ct);
 static string? ValidateTest(CreateVModelTestCaseRequest r){if(string.IsNullOrWhiteSpace(r.Title)||r.Title.Trim().Length>200)return"Title is required and must be 200 characters or fewer.";if(string.IsNullOrWhiteSpace(r.Description)||r.Description.Trim().Length>3000)return"Description is required and must be 3000 characters or fewer.";if(!Enum.IsDefined(r.TestLevel))return"The test level is invalid.";if(r.Preconditions?.Trim().Length>2000||string.IsNullOrWhiteSpace(r.TestSteps)||r.TestSteps.Trim().Length>5000||string.IsNullOrWhiteSpace(r.ExpectedResult)||r.ExpectedResult.Trim().Length>3000)return"Test steps and expected result are required and field limits must be respected.";if(r.ImplementationArtifactIds.Count==0)return"Select at least one implementation artifact.";if(r.ImplementationArtifactIds.Any(x=>x<=0)||r.ImplementationArtifactIds.Distinct().Count()!=r.ImplementationArtifactIds.Count)return"An implementation artifact selection is invalid or duplicated.";return null;}
 async Task<string> NextId(int pid,CancellationToken ct){var ids=await db.VModelTestCases.AsNoTracking().Where(x=>x.ProjectId==pid&&x.Identifier.StartsWith("TC-")).Select(x=>x.Identifier).ToListAsync(ct);int max=ids.Select(x=>int.TryParse(x.AsSpan(3),out int n)?n:0).DefaultIfEmpty().Max();return$"TC-{checked(max+1):D3}";}
 ActivityLog Audit(string action,string type,string id,int pid,string uid)=>new(){Action=action,ResourceType=type,ResourceId=id,ProjectId=pid,ActorUserId=uid,Description=action,CreatedAt=clock.UtcNow};static string? Opt(string? s)=>string.IsNullOrWhiteSpace(s)?null:s.Trim();static TestingOperationResult Ok(int? id,string m,string? identifier=null)=>TestingOperationResult.Success(id,m,identifier);static TestingOperationResult Invalid(string m)=>TestingOperationResult.Failed(TestingOperationFailure.Validation,m);static TestingOperationResult NotFound(string m)=>TestingOperationResult.Failed(TestingOperationFailure.NotFound,m);static TestingOperationResult Forbidden(string m="You are not authorized for this V-Model operation.")=>TestingOperationResult.Failed(TestingOperationFailure.Forbidden,m);static TestingOperationResult ReadOnly()=>TestingOperationResult.Failed(TestingOperationFailure.ReadOnly,"Archived projects are read-only.");static TestingOperationResult Conflict(string m)=>TestingOperationResult.Failed(TestingOperationFailure.Conflict,m);
 static bool Collision(DbUpdateException e){for(Exception? x=e;x is not null;x=x.InnerException)if(x is SqlException s&&s.Number is 2601 or 2627)return true;return false;}void Detach(IEnumerable<object> xs){foreach(var x in xs.Reverse())db.Entry(x).State=EntityState.Detached;}sealed record Actor(bool Admin,bool Manager,bool Qa,ProjectMemberRole? Role);
}
